### ISSUE TITLE
Using old bugged version of springloaded

### ISSUE THREAD

**Issue by ondrejvelisek** [OpenConext/OpenConext-authorization-admin#1]
Hello development team, 

When I was trying to run this project I was getting an exception. It was because of bug in springloaded version 1.2.1. More about bug:
https://github.com/spring-projects/spring-loaded/issues/98

I've solved it simply by rewrite version in your pom.xml (line 159) to version 1.2.5. I didn't try other versions. If you need some more info let me know.

Hope it helps

Ondrej

**Comment by oharsta** [comment]
Fixed in c4691db2289072f251cd2b5abbb5dc29c2620e25
