### ISSUE TITLE
Version Tag 2.0.11

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-authorization-admin#2]
Hello,

I noticed that OpenConext-Deploy is using version 2.0.11 of authorization admin, but the latest tagged version on GitHub for it is 2.0.10.

Would there be a way to get this tag pushed so our CI tool can grab it?

Much appreciated!

**Comment by oharsta** [comment]
https://github.com/OpenConext/OpenConext-authorization-admin/releases/tag/v2.0.11
